# [font]
# size = 12.0

# [font.normal]
# family = "JetBrainsMono"
# style = "Medium"

# [font.bold]
# family = "JetBrainsMono"
# style = "Heavy"

# [font.italic]
# family = "JetBrainsMono"
# style = "Italic"

# [font.bold_italic]
# family = "JetBrainsMono"
# style = "Heavy Italic"

# [window.padding]
# x = 15
# y = 15

[selection]
save_to_clipboard = true

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium"  # FiraCode 没有斜体

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold"  # FiraCode 没有粗斜体

[window.padding]
x = 15
y = 15

